//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceBSoap")]
    public interface WebServiceBSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tema del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarClase", ReplyAction="*")]
        ServiceReference1.AgregarClaseResponse AgregarClase(ServiceReference1.AgregarClaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarClase", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.AgregarClaseResponse> AgregarClaseAsync(ServiceReference1.AgregarClaseRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sinAlumnosResult del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sinAlumnos", ReplyAction="*")]
        ServiceReference1.sinAlumnosResponse sinAlumnos(ServiceReference1.sinAlumnosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sinAlumnos", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.sinAlumnosResponse> sinAlumnosAsync(ServiceReference1.sinAlumnosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularSueldo", ReplyAction="*")]
        double CalcularSueldo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularSueldo", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CalcularSueldoAsync();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerClaseResult del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerClase", ReplyAction="*")]
        ServiceReference1.ObtenerClaseResponse ObtenerClase(ServiceReference1.ObtenerClaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerClase", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ObtenerClaseResponse> ObtenerClaseAsync(ServiceReference1.ObtenerClaseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarClaseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarClase", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.AgregarClaseRequestBody Body;
        
        public AgregarClaseRequest()
        {
        }
        
        public AgregarClaseRequest(ServiceReference1.AgregarClaseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarClaseRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tema;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int cantidadGente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime fecha;
        
        public AgregarClaseRequestBody()
        {
        }
        
        public AgregarClaseRequestBody(string tema, int cantidadGente, System.DateTime fecha)
        {
            this.tema = tema;
            this.cantidadGente = cantidadGente;
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarClaseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarClaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.AgregarClaseResponseBody Body;
        
        public AgregarClaseResponse()
        {
        }
        
        public AgregarClaseResponse(ServiceReference1.AgregarClaseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AgregarClaseResponseBody
    {
        
        public AgregarClaseResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sinAlumnosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sinAlumnos", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.sinAlumnosRequestBody Body;
        
        public sinAlumnosRequest()
        {
        }
        
        public sinAlumnosRequest(ServiceReference1.sinAlumnosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class sinAlumnosRequestBody
    {
        
        public sinAlumnosRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sinAlumnosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sinAlumnosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.sinAlumnosResponseBody Body;
        
        public sinAlumnosResponse()
        {
        }
        
        public sinAlumnosResponse(ServiceReference1.sinAlumnosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sinAlumnosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.ArrayOfString sinAlumnosResult;
        
        public sinAlumnosResponseBody()
        {
        }
        
        public sinAlumnosResponseBody(ServiceReference1.ArrayOfString sinAlumnosResult)
        {
            this.sinAlumnosResult = sinAlumnosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerClaseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerClase", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ObtenerClaseRequestBody Body;
        
        public ObtenerClaseRequest()
        {
        }
        
        public ObtenerClaseRequest(ServiceReference1.ObtenerClaseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerClaseRequestBody
    {
        
        public ObtenerClaseRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerClaseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerClaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ObtenerClaseResponseBody Body;
        
        public ObtenerClaseResponse()
        {
        }
        
        public ObtenerClaseResponse(ServiceReference1.ObtenerClaseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerClaseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.ArrayOfString ObtenerClaseResult;
        
        public ObtenerClaseResponseBody()
        {
        }
        
        public ObtenerClaseResponseBody(ServiceReference1.ArrayOfString ObtenerClaseResult)
        {
            this.ObtenerClaseResult = ObtenerClaseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface WebServiceBSoapChannel : ServiceReference1.WebServiceBSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class WebServiceBSoapClient : System.ServiceModel.ClientBase<ServiceReference1.WebServiceBSoap>, ServiceReference1.WebServiceBSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebServiceBSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebServiceBSoapClient.GetBindingForEndpoint(endpointConfiguration), WebServiceBSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceBSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebServiceBSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceBSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebServiceBSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceBSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.AgregarClaseResponse ServiceReference1.WebServiceBSoap.AgregarClase(ServiceReference1.AgregarClaseRequest request)
        {
            return base.Channel.AgregarClase(request);
        }
        
        public void AgregarClase(string tema, int cantidadGente, System.DateTime fecha)
        {
            ServiceReference1.AgregarClaseRequest inValue = new ServiceReference1.AgregarClaseRequest();
            inValue.Body = new ServiceReference1.AgregarClaseRequestBody();
            inValue.Body.tema = tema;
            inValue.Body.cantidadGente = cantidadGente;
            inValue.Body.fecha = fecha;
            ServiceReference1.AgregarClaseResponse retVal = ((ServiceReference1.WebServiceBSoap)(this)).AgregarClase(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.AgregarClaseResponse> ServiceReference1.WebServiceBSoap.AgregarClaseAsync(ServiceReference1.AgregarClaseRequest request)
        {
            return base.Channel.AgregarClaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AgregarClaseResponse> AgregarClaseAsync(string tema, int cantidadGente, System.DateTime fecha)
        {
            ServiceReference1.AgregarClaseRequest inValue = new ServiceReference1.AgregarClaseRequest();
            inValue.Body = new ServiceReference1.AgregarClaseRequestBody();
            inValue.Body.tema = tema;
            inValue.Body.cantidadGente = cantidadGente;
            inValue.Body.fecha = fecha;
            return ((ServiceReference1.WebServiceBSoap)(this)).AgregarClaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.sinAlumnosResponse ServiceReference1.WebServiceBSoap.sinAlumnos(ServiceReference1.sinAlumnosRequest request)
        {
            return base.Channel.sinAlumnos(request);
        }
        
        public ServiceReference1.ArrayOfString sinAlumnos()
        {
            ServiceReference1.sinAlumnosRequest inValue = new ServiceReference1.sinAlumnosRequest();
            inValue.Body = new ServiceReference1.sinAlumnosRequestBody();
            ServiceReference1.sinAlumnosResponse retVal = ((ServiceReference1.WebServiceBSoap)(this)).sinAlumnos(inValue);
            return retVal.Body.sinAlumnosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.sinAlumnosResponse> ServiceReference1.WebServiceBSoap.sinAlumnosAsync(ServiceReference1.sinAlumnosRequest request)
        {
            return base.Channel.sinAlumnosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.sinAlumnosResponse> sinAlumnosAsync()
        {
            ServiceReference1.sinAlumnosRequest inValue = new ServiceReference1.sinAlumnosRequest();
            inValue.Body = new ServiceReference1.sinAlumnosRequestBody();
            return ((ServiceReference1.WebServiceBSoap)(this)).sinAlumnosAsync(inValue);
        }
        
        public double CalcularSueldo()
        {
            return base.Channel.CalcularSueldo();
        }
        
        public System.Threading.Tasks.Task<double> CalcularSueldoAsync()
        {
            return base.Channel.CalcularSueldoAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.ObtenerClaseResponse ServiceReference1.WebServiceBSoap.ObtenerClase(ServiceReference1.ObtenerClaseRequest request)
        {
            return base.Channel.ObtenerClase(request);
        }
        
        public ServiceReference1.ArrayOfString ObtenerClase()
        {
            ServiceReference1.ObtenerClaseRequest inValue = new ServiceReference1.ObtenerClaseRequest();
            inValue.Body = new ServiceReference1.ObtenerClaseRequestBody();
            ServiceReference1.ObtenerClaseResponse retVal = ((ServiceReference1.WebServiceBSoap)(this)).ObtenerClase(inValue);
            return retVal.Body.ObtenerClaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ObtenerClaseResponse> ServiceReference1.WebServiceBSoap.ObtenerClaseAsync(ServiceReference1.ObtenerClaseRequest request)
        {
            return base.Channel.ObtenerClaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ObtenerClaseResponse> ObtenerClaseAsync()
        {
            ServiceReference1.ObtenerClaseRequest inValue = new ServiceReference1.ObtenerClaseRequest();
            inValue.Body = new ServiceReference1.ObtenerClaseRequestBody();
            return ((ServiceReference1.WebServiceBSoap)(this)).ObtenerClaseAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceBSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceBSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceBSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50146/WebServiceB.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceBSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50146/WebServiceB.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebServiceBSoap,
            
            WebServiceBSoap12,
        }
    }
}
